# -*- coding: utf-8 -*-
"""customerName

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/141h9UNGObwBnWBduxmgvBI2hfUVNs9YV
"""

#Script file for giving information about the customer who is using the simulator
class customerPerson():
  #init method or constructor
  def _init_(self,name):
    self.name = name
    self.money = 1000
    print("Person name : " + self.name.title())
    print("Person money : $" + str(self.money).title())