# -*- coding: utf-8 -*-
"""flask

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IgCOiKYwJ6oAsr_yJ6Gs3WVrJkef4k5d
"""



from flask import Flask
import setup.py # this will be your file name; minus the `.py`

app = Flask(__name__)

@app.route('/')
def dynamic_page():
    return setup.py.your_function_in_the_module()

if __name__ == '__main__':
    app.run(host='0.0.0.0', port='8000', debug=True)