# -*- coding: utf-8 -*-
"""testFlask

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IgCOiKYwJ6oAsr_yJ6Gs3WVrJkef4k5d
"""



# Importing flask module in the project is mandatory
# An object of Flask class is our WSGI application.
from flask import Flask, render_template, request
import setup.py
# Flask constructor takes the name of
# current module (__name__) as argument.
app = Flask(__name__)

# The route() function of the Flask class is a decorator,
# which tells the application which URL should call
# the associated function.

@app.route('/')
def index():
    return render_template('index.html')
    
@app.route('/')
# ‘/’ URL is bound with hello_world() function.
def dynamic_page():
    return setup.py.your_function_in_the_module()


# main driver function
if __name__ == '__main__':
    app.debug = True
    # run() method of Flask class runs the application
    # on the local development server.
    app.run()
